package routes

import (
	"bast-request/internal/handlers"
	"bast-request/internal/middlewares"
	"bast-request/internal/repositories"
	"bast-request/internal/services"
	_ "bast-request/docs" // generated by swag init

	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
	"gorm.io/gorm"
)

// SetupRoutes registers all API routes
func SetupRoutes(r *gin.Engine, db *gorm.DB) {
	// Initialize Dependencies
	customerRepo := repositories.NewCustomerRepository(db)
	customerService := services.NewCustomerService(customerRepo)
	customerHandler := handlers.NewCustomerHandler(customerService)

	projectRepo := repositories.NewProjectRepository(db)
	projectService := services.NewProjectService(projectRepo)
	projectHandler := handlers.NewProjectHandler(projectService)

	formatRepo := repositories.NewBastFormatRepository(db)
	formatService := services.NewBastFormatService(formatRepo)
	formatHandler := handlers.NewBastFormatHandler(formatService)

	seqRepo := repositories.NewBastSequenceRepository(db)
	seqService := services.NewBastSequenceService(seqRepo)
	seqHandler := handlers.NewBastSequenceHandler(seqService)

	requestRepo := repositories.NewBastRequestRepository(db)
	requestService := services.NewBastRequestService(requestRepo, formatService, seqService)
	requestHandler := handlers.NewBastRequestHandler(requestService)

	auditRepo := repositories.NewAuditLogRepository(db)
	auditService := services.NewAuditLogService(auditRepo)
	auditHandler := handlers.NewAuditLogHandler(auditService)

	authRepo := repositories.NewAuthRepository(db)
	authService := services.NewAuthService(authRepo)
	authHandler := handlers.NewAuthHandler(authService)

	api := r.Group("/api")
	{
		// Auth Endpoint Publik
		api.POST("/auth/register", authHandler.Register)
		api.POST("/auth/login", authHandler.Login)

		// Endpoint Terlindungi (Semua butuh Token JWT valid)
		protected := api.Group("/")
		protected.Use(middlewares.RequireAuth()) 
		{
			// Bisa diakses oleh siapapun asalkan punya Token
			protected.GET("/projects", projectHandler.GetAllProjects) // Example protected route
			
			// Hanya bisa diakses oleh Superadmin dan Admin
			adminOnly := protected.Group("/")
			adminOnly.Use(middlewares.RequireRole("superadmin", "admin"))
			{
				adminOnly.POST("/projects", projectHandler.CreateProject)
				adminOnly.DELETE("/customers/:id", customerHandler.DeleteCustomer)
			}
			
			// MASTER CUSTOMER
			protected.GET("/customers", customerHandler.GetAllCustomers)
			protected.GET("/customers/:id", customerHandler.GetCustomerByID)
			protected.POST("/customers", customerHandler.CreateCustomer)
			protected.PUT("/customers/:id", customerHandler.UpdateCustomer)

			// MASTER PROJECT
			protected.GET("/projects/:id", projectHandler.GetProjectByID)
			protected.PUT("/projects/:id", projectHandler.UpdateProject)
			protected.DELETE("/projects/:id", projectHandler.DeleteProject)

			// MASTER FORMAT NOMOR BAST
			protected.GET("/bast-formats", formatHandler.GetAllFormats)
			protected.GET("/bast-formats/:id", formatHandler.GetFormatByID)
			protected.POST("/bast-formats", formatHandler.CreateFormat)
			protected.PUT("/bast-formats/:id", formatHandler.UpdateFormat)
			protected.DELETE("/bast-formats/:id", formatHandler.DeleteFormat)

			// RUNNING NUMBER (BAST SEQUENCE)
			protected.GET("/bast-sequences", seqHandler.GetSequence)
			protected.POST("/bast-sequences/reset", seqHandler.ResetSequence)

			// REQUEST NOMOR BAST
			protected.GET("/bast-requests", requestHandler.GetAllRequests)
			protected.GET("/bast-requests/:id", requestHandler.GetRequestByID)
			protected.POST("/bast-requests", requestHandler.CreateRequest)
			protected.PATCH("/bast-requests/:id/status", requestHandler.UpdateStatus)
			protected.GET("/bast-requests/:id/audit", requestHandler.GetRequestAudit)

			// AUDIT LOG
			protected.GET("/audit-logs", auditHandler.GetAllAuditLogs)
			protected.GET("/audit-logs/:id", auditHandler.GetAuditLogByID)

		}
	}

	// Swagger documentation route
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
}